### ISSUE TITLE
Looking for guidance with libtorrent integration, whatever you've got.

### ISSUE THREAD

**Issue by ibsusu** [rawrtc/rawrtc-terminal-demo#18]
I'm trying to integrate rawrtc into libtorrent, transmission, and rtorrent.  I've read your opinions on websockets vs webrtc and think you're right, especially when [this](https://w3c.github.io/webrtc-quic/) is considered.  This whole situation really makes me just want udp browser capability but whatever.

With that said, I'm starting here:
https://github.com/rawrtc/rawrtc-terminal-demo/blob/master/c/src/rawrtc-terminal.c#L800
and I'd like any tips, shortcuts or thoughts you might have regarding how to best go about this for libtorrent.

I would _very_ much appreciate anything you can provide but I will make the code work some how.  If it wasn't for you I would just use [uwebsockets](https://github.com/uNetworking/uWebSockets) with redirects or something so thanks.

**Comment by lgrahl** [comment]
Don't use this project as a starting point, use https://github.com/rawrtc/rawrtc/blob/master/tools/peer-connection.c instead. This demo has been created prior to the addition of the WebRTC API into RAWRTC. Before that, we only had the flexible and more low-level ORTC API.

I'm unaware of the design of libtorrent, so I can't really give guidance on how to integrate it. If it's thread-based, see the [hints in the FAQ](https://github.com/rawrtc/rawrtc/blob/master/README.md#faq).

Something you should be aware of is that Windows support is currently an issue due to the dependencies. re doesn't compile with MSVC and usrsctp doesn't compile with MinGW. I currently do not have time to investigate this myself. This may or may not be easy to fix.

If you have further questions, please join [our Gitter chat](https://gitter.im/rawrtc/Lobby).
