### ISSUE TITLE
Why RawRTC and not SaltyRTC?

### ISSUE THREAD

**Issue by rugk** [rawrtc/rawrtc-terminal-demo#4]
Why do you use RAWRTC?

**Comment by lgrahl** [comment]
RAWRTC is an ORTC/WebRTC implementation whereas SaltyRTC is a signalling solution. They are not mutually exclusive. This demo does not use SaltyRTC because there is no SaltyRTC implementation in C.

Moreover, we are probably going to remove the WS-based signalling (which was a requirement for our studies) from this demo to make it as simple as possible. The result will be called copy & paste signalling which is also pretty secure. ;)

**Comment by rugk** [comment]
Copy and paste signalling?? So you must copy and paste as token or so to the other device?

**Comment by lgrahl** [comment]
WS-based = WebSocket-based. Currently, this demo uses an extremely brittle signalling over WebSocket. This will be removed as we don't want to require users to set up a signalling server, nor do we want to provide one permanently.

It is a demo application for our WebRTC/ORTC implementation. And as you probably know, WebRTC purposely does not specify how signalling is done. So, for a WebRTC/ORTC demo, copy & pasting the whole signalling data is fine.

**Comment by rugk** [comment]
Ah, indeed. For a demo that's okay… :laughing: 

Just sounds funny if you image a real use case… :smiley:

**Comment by Globik** [comment]
The same here. Why fd stdin?

**Comment by Globik** [comment]
@rugk  not ok.

**Comment by lgrahl** [comment]
@Globik As explained dozens of times now in our Gitter channel, the demo uses **both** a WebSocket server and stdin for signalling. **Both** can be used. It is **entirely optional** which to choose and if you want to you can remove all the code related to stdin and it will still work. I kindly ask you to not dig up old issues for asking the same question again.
